### ISSUE TITLE
Negative KL divergence values

### ISSUE THREAD

**Issue by Maze55555** [felipemaiapolo/detectshift#1]
I have to congratulate you first on a great work done with this package. I think it will enable a lot of future work related to dataset shift.
My question is about my observation that this implementation sometimes produces negative values of the KL divergence. You did acknowledge in the paper that KL divergence is always non-negative. Is there an explanation for this?

**Comment by felipemaiapolo** [comment]
Hi there,

Thank you for your kind words. Two possible explanations for this are that: (i) your probabilistic classifier is potentially misspecified, or (ii) your sample size is not big enough. Since we do not observe the true distributions or the density ratio (R-N derivative), the calculation can lead to negative estimates for the KL. This should not be a big problem if you also perform the hypothesis testing procedure (sometimes the p-value for Y|X can be misleading as well, it all depends on your model specification). 

Does this help?

**Comment by Maze55555** [comment]
Ah that makes sense as the p-values of the hypothesis test tend to be relatively larger when the KL divergence is negative. 
Thank you for the quick response.

**Comment by felipemaiapolo** [comment]
No problem!

I'll close this issue. Please open another one or email me if you have other questions.
